/* Audio — synthesized via WebAudio, no asset files.
 *
 * Goal: evoke the 1979 Asteroids cabinet, not perfectly reproduce it. The original
 * sound is generated by analog circuits with specific nonlinearities WebAudio can
 * approximate but not match. What we CAN do is match the *character*:
 *
 *   - Thrust is a *growling engine*, not a hum. (Frequency-modulated rumble.)
 *   - Fire is a *tight percussive click* with a fast decay.
 *   - Boom is a *wide-band crash* with a sharp envelope — not a muffled thud.
 *   - UFO big is the *iconic "wub-wub-wub"* — amplitude-modulated, not flat.
 *   - UFO small is the same idea, faster and higher pitched.
 *
 * All sounds gated on user-initiated audio context (browser autoplay policy).
 */

const Audio = (() => {
  let ctx = null;
  let masterGain = null;
  let muted = false;

  // Persistent state for ongoing sounds
  let thrustOsc = null;
  let thrustLfo = null;       // modulates thrustOsc frequency for the growl
  let thrustGain = null;
  let thrustLfoGain = null;
  let thrustActive = false;

  // UFO oscillators (persistent, amplitude-modulated for the "wub-wub-wub")
  let ufoOsc = null;
  let ufoLfo = null;          // modulates the UFO amplitude (the wub)
  let ufoGain = null;
  let ufoLfoGain = null;

  function init() {
    if (ctx) return;
    const Ctx = window.AudioContext || window.webkitAudioContext;
    if (!Ctx) return;
    ctx = new Ctx();
    masterGain = ctx.createGain();
    masterGain.gain.value = 0.35;
    masterGain.connect(ctx.destination);

    // ----- Thrust chain -----
    // A sawtooth oscillator whose frequency is modulated by a slow LFO at ~12Hz,
    // giving it the characteristic engine growl.
    thrustOsc = ctx.createOscillator();
    thrustOsc.type = "sawtooth";
    thrustOsc.frequency.value = 60;
    thrustLfo = ctx.createOscillator();
    thrustLfo.type = "sine";
    thrustLfo.frequency.value = 12;          // growl rate
    thrustLfoGain = ctx.createGain();
    thrustLfoGain.gain.value = 14;           // modulation depth in Hz
    thrustLfo.connect(thrustLfoGain).connect(thrustOsc.frequency);
    thrustGain = ctx.createGain();
    thrustGain.gain.value = 0;
    // Lowpass on thrust to avoid the harsh sawtooth bite
    const thrustFilter = ctx.createBiquadFilter();
    thrustFilter.type = "lowpass";
    thrustFilter.frequency.value = 400;
    thrustOsc.connect(thrustFilter).connect(thrustGain).connect(masterGain);
    thrustOsc.start();
    thrustLfo.start();

    // ----- UFO chain -----
    // A square wave with amplitude modulated by a slow LFO at ~8Hz, giving
    // the iconic "wub-wub-wub". LFO depth is high so the amplitude swings
    // nearly to silence — that's the recognizable pulsing.
    //
    // CRITICAL: ufoLfoGain starts at 0. The depth is set by ufoSetSize()
    // when a UFO actually spawns. Setting it nonzero at init produces a
    // continuous warbling warble on the first keypress (which calls
    // Audio.unlock → init), even with no UFO on screen.
    ufoOsc = ctx.createOscillator();
    ufoOsc.type = "triangle";
    ufoOsc.frequency.value = 60;
    ufoGain = ctx.createGain();
    ufoGain.gain.value = 0; // start silent
    const ufoFilter = ctx.createBiquadFilter();
    ufoFilter.type = "lowpass";
    ufoFilter.frequency.value = 1200;
    // LFO for amplitude (the wub) — swings gain between near-silence and full volume.
    // Depth is set to 0 here and tuned by ufoSetSize() when a UFO spawns.
    ufoLfo = ctx.createOscillator();
    ufoLfo.type = "sine";
    ufoLfo.frequency.value = 8;
    ufoLfoGain = ctx.createGain();
    ufoLfoGain.gain.value = 0; // start with zero modulation depth → silent
    ufoLfo.connect(ufoLfoGain).connect(ufoGain.gain);
    ufoOsc.connect(ufoFilter).connect(ufoGain).connect(masterGain);
    ufoOsc.start();
    ufoLfo.start();
  }

  function unlock() {
    if (!ctx) init();
    if (ctx && ctx.state === "suspended") ctx.resume();
  }

  function blip(freq, durMs, type = "square", vol = 0.3) {
    if (!ctx || muted) return;
    const t = ctx.currentTime;
    const osc = ctx.createOscillator();
    const gain = ctx.createGain();
    osc.type = type;
    osc.frequency.setValueAtTime(freq, t);
    gain.gain.setValueAtTime(vol, t);
    gain.gain.exponentialRampToValueAtTime(0.001, t + durMs / 1000);
    osc.connect(gain).connect(masterGain);
    osc.start(t);
    osc.stop(t + durMs / 1000 + 0.02);
  }

  function noise(durMs, vol = 0.3, filterFreq = 1200, filterQ = 1) {
    if (!ctx || muted) return;
    const t = ctx.currentTime;
    const bufferSize = Math.floor(ctx.sampleRate * (durMs / 1000));
    const buffer = ctx.createBuffer(1, bufferSize, ctx.sampleRate);
    const data = buffer.getChannelData(0);
    // Linear envelope from full to zero (not random envelope — sharper)
    for (let i = 0; i < bufferSize; i++) {
      const env = 1 - i / bufferSize;
      data[i] = (Math.random() * 2 - 1) * env;
    }
    const src = ctx.createBufferSource();
    src.buffer = buffer;
    const filter = ctx.createBiquadFilter();
    filter.type = "lowpass";
    filter.frequency.value = filterFreq;
    filter.Q.value = filterQ;
    const gain = ctx.createGain();
    gain.gain.setValueAtTime(vol, t);
    gain.gain.exponentialRampToValueAtTime(0.001, t + durMs / 1000);
    src.connect(filter).connect(gain).connect(masterGain);
    src.start(t);
  }

  // --- Game-specific events ---

  function fire() {
    if (!ctx || muted) return;
    // OG fire is a tight percussive click + brief tone. Two layers:
    // 1. High-passed noise burst (the "click")
    // 2. Brief square tone at ~880Hz (the "report")
    const t = ctx.currentTime;
    // Click: very short noise burst
    const clickBufSize = Math.floor(ctx.sampleRate * 0.04);
    const buf = ctx.createBuffer(1, clickBufSize, ctx.sampleRate);
    const data = buf.getChannelData(0);
    for (let i = 0; i < clickBufSize; i++) {
      data[i] = (Math.random() * 2 - 1) * (1 - i / clickBufSize);
    }
    const src = ctx.createBufferSource();
    src.buffer = buf;
    const hp = ctx.createBiquadFilter();
    hp.type = "highpass";
    hp.frequency.value = 2000;
    const clickGain = ctx.createGain();
    clickGain.gain.setValueAtTime(0.18, t);
    clickGain.gain.exponentialRampToValueAtTime(0.001, t + 0.04);
    src.connect(hp).connect(clickGain).connect(masterGain);
    src.start(t);

    // Report: short square tone with fast decay
    const osc = ctx.createOscillator();
    const gain = ctx.createGain();
    osc.type = "square";
    osc.frequency.setValueAtTime(880, t);
    osc.frequency.exponentialRampToValueAtTime(440, t + 0.06); // pitch drop
    gain.gain.setValueAtTime(0.15, t);
    gain.gain.exponentialRampToValueAtTime(0.001, t + 0.08);
    osc.connect(gain).connect(masterGain);
    osc.start(t);
    osc.stop(t + 0.1);
  }

  function boom() {
    if (!ctx || muted) return;
    // OG boom is a wide-band crash. The mistake in v0.1 was over-lowpassing it,
    // which made it sound muffled. Use less lowpass and a sharper envelope.
    // Layer 1: full-spectrum noise burst, sharper envelope
    noise(180, 0.35, 1800, 2);
    // Layer 2: a low sawtooth "thump" for body
    blip(90, 200, "sawtooth", 0.25);
  }

  function thrust(on) {
    if (!ctx || !thrustGain || muted) return;
    thrustActive = on;
    const t = ctx.currentTime;
    thrustGain.gain.cancelScheduledValues(t);
    // Smoother fade-in/out so it doesn't pop
    thrustGain.gain.setTargetAtTime(on ? 0.18 : 0, t, 0.04);
  }

  // UFO big: deep slow "wub-wub-wub"
  // UFO small: higher pitch, faster wobble
  // We set the oscillator frequency and LFO rate/size based on size.
  function ufoSetSize(size) {
    if (!ctx || !ufoOsc || !ufoLfo || !ufoLfoGain) return;
    if (size === "small") {
      // Small UFO: higher fundamental (110Hz, like an octave above the
      // original 55), faster wobble (9Hz).
      ufoOsc.frequency.value = 110;
      ufoLfo.frequency.value = 9;
      ufoLfoGain.gain.value = 0.10;
    } else {
      // Big UFO: low fundamental (55Hz, deep bass), slow wobble (6Hz).
      ufoOsc.frequency.value = 55;
      ufoLfo.frequency.value = 6;
      ufoLfoGain.gain.value = 0.11;
    }
  }

  // ---- Background drone ----
  // The iconic OG Asteroids low-frequency tone that throbs with the
  // number of active objects on screen. Implemented as a triangle-wave
  // oscillator with its GAIN modulated by an LFO; the LFO rate is set
  // externally by the game based on object count. Fewer objects → slower
  // throb. More objects → faster throb (cap so it never gets frantic).
  //
  // The user described it as a Jaws-like note that intensifies with field
  // density. Lower-frequency fundamental + slow LFO = ominous; higher LFO
  // rate = rising tension. We use a fixed low fundamental and vary only
  // the modulation rate; the OG hardware had a similar single-axis scheme.
  let droneOsc = null;
  let droneGain = null;
  let droneLfo = null;
  let droneLfoDepth = null; // gain node: depth = how much the LFO modulates droneGain

  function droneStart() {
    if (!ctx || droneOsc) return;
    droneOsc = ctx.createOscillator();
    droneOsc.type = "triangle";
    droneOsc.frequency.value = 55; // A1 — deep bass
    droneGain = ctx.createGain();
    droneGain.gain.value = 0; // start silent — droneUpdate ramps it in
    droneLfo = ctx.createOscillator();
    droneLfo.type = "sine";
    droneLfo.frequency.value = 1.0; // 1 Hz by default — slow throb
    droneLfoDepth = ctx.createGain();
    droneLfoDepth.gain.value = 0.06; // how much the throb modulates the drone gain
    // LFO → depth → droneGain.gain. The drone gain sits at the LFO's offset (0)
    // plus the depth (0.06). So the gain oscillates between -0.06 and +0.06.
    // WebAudio clamps negative gain... wait, it doesn't (negative gain inverts
    // phase). We need a positive base. So droneGain.gain = 0.08 + lfo*0.05.
    // The simplest fix: set droneGain.gain.value to a positive constant, then
    // modulate around it via a node that adds to it.
    droneGain.gain.value = 0.08;
    droneLfo.connect(droneLfoDepth).connect(droneGain.gain);
    droneOsc.connect(droneGain).connect(masterGain);
    droneOsc.start();
    droneLfo.start();
  }

  function droneStop() {
    if (droneOsc) {
      try { droneOsc.stop(); } catch (e) {}
      droneOsc.disconnect();
      droneOsc = null;
    }
    if (droneLfo) {
      try { droneLfo.stop(); } catch (e) {}
      droneLfo.disconnect();
      droneLfo = null;
    }
    if (droneGain) {
      droneGain.disconnect();
      droneGain = null;
    }
    droneLfoDepth = null;
  }

  // Set the throb rate based on the number of active objects on screen.
  // objectCount is total = asteroids + bullets + ufos + 1 (for the ship).
  // Map to a throb rate in Hz. Few objects → slow (1.0 Hz). Many → fast (4.0 Hz).
  function droneSetObjectCount(objectCount) {
    if (!ctx || !droneLfo) return;
    // Clamp the count to keep the rate in a sensible range.
    const c = Math.max(0, Math.min(objectCount, 30));
    // Linear: rate = 1 + (c/30) * 3 → 1 Hz at 0 objects, 4 Hz at 30 objects.
    const rate = 1.0 + (c / 30) * 3.0;
    droneLfo.frequency.setTargetAtTime(rate, ctx.currentTime, 0.1);
  }

  function ufoActive(on) {
    if (!ctx || !ufoGain || muted) return;
    const t = ctx.currentTime;
    ufoGain.gain.cancelScheduledValues(t);
    if (on) {
      // Restore the modulation depth so the LFO modulates the gain around
      // the new base. (ufoSetSize is also called separately to set the
      // per-size depth, but setting it here too covers the case where the
      // UFO's been off-screen long enough that the depth got ramped to 0.)
      ufoLfoGain.gain.setTargetAtTime(ufoLfoGain.gain.value || 0.09, t, 0.05);
      ufoGain.gain.setTargetAtTime(0.10, t, 0.05);
    } else {
      // CRITICAL: ramp the LFO depth to 0 alongside the base gain.
      // Otherwise the LFO oscillates ufoGain.gain around 0 with amplitude
      // ±0.09 → gain swings between -0.09 and +0.09. WebAudio's GainNode
      // does NOT clamp negative values (it inverts phase), so the +0.09
      // peaks produce audible warbling even after ufoActive(false).
      // Ramping the depth to 0 kills the modulation entirely.
      ufoLfoGain.gain.setTargetAtTime(0, t, 0.05);
      ufoGain.gain.setTargetAtTime(0, t, 0.05);
    }
  }

  // Backwards-compat shims (the old API had separate ufoBig/ufoSmall/ufoFire).
  // The game now calls ufoActive(true/false) and ufoSetSize().
  function ufoBig() { ufoSetSize("big"); ufoActive(true); }
  function ufoSmall() { ufoSetSize("small"); ufoActive(true); }
  function ufoFire() {
    if (!ctx || muted) return;
    // Slightly different envelope for big vs small fire, but the game calls this
    // for both. Make it neutral.
    blip(660, 50, "square", 0.2);
  }

  function extraLife() {
    if (!ctx || muted) return;
    // The actual OG extra-life tune is a recognizable ascending arpeggio.
    // Mine approximates: 440 → 660 → 880 over ~450ms total.
    blip(440, 120, "square", 0.22);
    setTimeout(() => blip(660, 120, "square", 0.22), 120);
    setTimeout(() => blip(880, 220, "square", 0.22), 240);
  }

  function gameOver() {
    if (!ctx || muted) return;
    // 3-note descending — the iconic "game over" cadence.
    blip(220, 200, "sawtooth", 0.3);
    setTimeout(() => blip(180, 200, "sawtooth", 0.3), 220);
    setTimeout(() => blip(140, 400, "sawtooth", 0.3), 440);
  }

  function setMuted(m) {
    muted = m;
    if (masterGain) masterGain.gain.value = m ? 0 : 0.35;
    // Also gate persistent sounds so they don't keep playing silently
    if (m) {
      thrust(false);
      ufoActive(false);
    } else if (thrustActive) {
      thrust(true);
    }
  }

  return {
    init, unlock,
    fire, boom, thrust,
    ufoBig, ufoSmall, ufoFire, ufoSetSize, ufoActive,
    droneStart, droneStop, droneSetObjectCount,
    extraLife, gameOver,
    setMuted,
  };
})();
